import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Link,
  Preview,
  Section,
  Text,
} from '@react-email/components';
import type { RoadmapEmailModel } from '@/lib/email/roadmap-email-model';

const base = '#0A0A0A';
const surface = '#141414';
const text = '#F5F0E8';
const accent = '#FF4D00';
const muted = '#888888';
const border = 'rgba(245, 240, 232, 0.12)';

export interface RoadmapEmailProps extends RoadmapEmailModel {
  strategyCtaUrl: string;
}

export default function RoadmapEmail({
  recipientFirstName,
  companyLine,
  topPriorities,
  phases,
  primaryServiceTitle,
  primaryServiceBlurb,
  secondaryServiceTitle,
  secondaryServiceBlurb,
  engagementPathTitle,
  engagementPathRationale,
  sprintTitle,
  strategyCtaUrl,
}: RoadmapEmailProps) {
  return (
    <Html>
      <Head />
      <Preview>Your 90-day marketing roadmap — priorities, phases, and recommended next steps.</Preview>
      <Body style={main}>
        <Container style={container}>
          <Section style={header}>
            <Text style={eyebrow}>
              <span style={{ color: text }}>Darling </span>
              <span style={{ color: accent }}>MarTech</span>
              <span style={{ color: muted }}> · Roadmap</span>
            </Text>
            <Heading as="h1" style={h1}>
              Your 90-day marketing roadmap
            </Heading>
          </Section>

          <Text style={paragraph}>Hi {recipientFirstName},</Text>
          {companyLine ? (
            <Text style={paragraph}>Thanks for requesting this — we noted your company as {companyLine}.</Text>
          ) : (
            <Text style={paragraph}>Thanks for requesting your roadmap summary.</Text>
          )}
          <Text style={paragraph}>
            Below is a concise, scannable overview of your deterministic plan. For full module detail
            and explainability, revisit your results page or the share link you used.
          </Text>

          <Heading as="h2" style={h2}>
            Top 3 priorities
          </Heading>
          <Section style={listBox}>
            {topPriorities.map((p, i) => (
              <Text key={p} style={listItem}>
                <strong style={{ color: accent }}>{i + 1}.</strong> {p}
              </Text>
            ))}
          </Section>

          <Heading as="h2" style={h2}>
            90-day roadmap by phase
          </Heading>
          {phases.map((phase) => (
            <Section key={phase.phaseLabel} style={phaseBlock}>
              <Text style={phaseTitle}>
                <strong style={{ color: text }}>
                  {phase.phaseLabel}: {phase.phaseTitle}
                </strong>{' '}
                <span style={{ color: muted, fontWeight: 400 }}>({phase.days})</span>
              </Text>
              {phase.moduleTitles.map((t) => (
                <Text key={t} style={bullet}>
                  • {t}
                </Text>
              ))}
            </Section>
          ))}

          <Hr style={hr} />

          <Heading as="h2" style={h2}>
            Recommended services
          </Heading>
          <Text style={label}>Primary</Text>
          <Text style={strongLine}>{primaryServiceTitle}</Text>
          <Text style={mutedParagraph}>{primaryServiceBlurb}</Text>
          <Text style={label}>Supporting</Text>
          <Text style={strongLine}>{secondaryServiceTitle}</Text>
          <Text style={mutedParagraph}>{secondaryServiceBlurb}</Text>

          <Heading as="h2" style={h2}>
            Recommended engagement path
          </Heading>
          <Text style={strongLine}>{engagementPathTitle}</Text>
          <Text style={mutedParagraph}>{engagementPathRationale}</Text>

          <Text style={label}>Sprint / program shape</Text>
          <Text style={paragraph}>{sprintTitle}</Text>

          <Hr style={hr} />

          <Section style={ctaBox}>
            <Text style={ctaText}>
              Ready to pressure-test this plan with your calendar and budget?
            </Text>
            <Text style={ctaSubline}>Walk through your roadmap on a short call — sequencing, tradeoffs, and what to fund first.</Text>
            <Button href={strategyCtaUrl} style={button}>
              Book a strategy conversation
            </Button>
            <Text style={footerNote}>
              If the button does not work, copy this link:{' '}
              <Link href={strategyCtaUrl} style={link}>
                {strategyCtaUrl}
              </Link>
            </Text>
          </Section>

          <Text style={disclaimer}>
            This roadmap was generated by a deterministic rules engine from your intake answers — not
            by AI. Results are for planning purposes; engagement terms are confirmed separately.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

const main = {
  backgroundColor: base,
  fontFamily:
    'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
};

const container = {
  margin: '0 auto',
  padding: '32px 24px',
  maxWidth: '560px',
};

const header = {
  marginBottom: '24px',
};

const eyebrow = {
  fontSize: '12px',
  fontWeight: 800,
  letterSpacing: '-0.02em',
  margin: '0 0 12px',
};

const h1 = {
  color: text,
  fontSize: '26px',
  fontWeight: 800,
  lineHeight: '1.15',
  margin: '0',
  letterSpacing: '-0.02em',
};

const h2 = {
  color: text,
  fontSize: '17px',
  fontWeight: 800,
  margin: '28px 0 12px',
  letterSpacing: '-0.02em',
};

const paragraph = {
  color: text,
  fontSize: '15px',
  lineHeight: '1.6',
  margin: '0 0 16px',
};

const mutedParagraph = {
  color: muted,
  fontSize: '14px',
  lineHeight: '1.55',
  margin: '0 0 16px',
};

const listBox = {
  backgroundColor: surface,
  border: `1px solid ${border}`,
  borderRadius: '16px',
  padding: '16px 20px',
  marginBottom: '8px',
};

const listItem = {
  color: text,
  fontSize: '14px',
  lineHeight: '1.5',
  margin: '0 0 8px',
};

const phaseBlock = {
  backgroundColor: surface,
  border: `1px solid ${border}`,
  borderRadius: '16px',
  padding: '14px 18px',
  marginBottom: '12px',
};

const phaseTitle = {
  color: text,
  fontSize: '14px',
  margin: '0 0 8px',
};

const bullet = {
  color: muted,
  fontSize: '13px',
  lineHeight: '1.45',
  margin: '0 0 4px 8px',
};

const label = {
  fontSize: '11px',
  fontWeight: 600,
  textTransform: 'uppercase' as const,
  letterSpacing: '0.08em',
  color: accent,
  margin: '16px 0 6px',
};

const strongLine = {
  color: text,
  fontSize: '15px',
  fontWeight: 600,
  margin: '0 0 6px',
};

const hr = {
  borderColor: border,
  margin: '28px 0',
};

const ctaBox = {
  textAlign: 'center' as const,
  marginTop: '8px',
};

const ctaText = {
  color: text,
  fontSize: '15px',
  margin: '0 0 8px',
};

const ctaSubline = {
  color: muted,
  fontSize: '14px',
  lineHeight: '1.55',
  margin: '0 0 18px',
};

const button = {
  backgroundColor: accent,
  color: base,
  fontSize: '15px',
  fontWeight: 700,
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  padding: '14px 28px',
  borderRadius: '999px',
};

const footerNote = {
  fontSize: '12px',
  color: muted,
  margin: '20px 0 0',
  lineHeight: '1.5',
  wordBreak: 'break-all' as const,
};

const link = {
  color: accent,
};

const disclaimer = {
  fontSize: '12px',
  color: muted,
  lineHeight: '1.5',
  margin: '32px 0 0',
};
